//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroCrud
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class test_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public test_usuario()
        {
            this.test_habilidades_usuario = new HashSet<test_habilidades_usuario>();
        }

        [Required(ErrorMessage = "La cedula es requerida")]
        public string usu_ced { get; set; }

        [Required(ErrorMessage = "El tipo de usuario es requerido")]
        public string usu_tipoUsuario { get; set; }

        [Required(ErrorMessage = "El nombre completo es requerido")]
        public string usu_nombreCompleto { get; set; }
        public string usu_correo { get; set; }
        public string usu_tipoIdent { get; set; }

        [Required(ErrorMessage = "El nombre de usuario es requerido")]
        public string usu_usuario { get; set; }
        public string usu_clave { get; set; }
        public string usu_activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<test_habilidades_usuario> test_habilidades_usuario { get; set; }
    }

    public class test_habilidades_ 
    {
        public string hab_id { get; set; }
        public string hab_nombre { get; set; }

        public bool check { get; set; }
    }
}
